name: Build and Deploy FastAPI App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy FastAPI App
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/weather-api:latest

      - name: Deploy to VPS via SSH
        env:
          APP_NAME: weather-api
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p "${{ secrets.SSH_PORT }}" -o StrictHostKeyChecking=no "${{ secrets.USERNAME_AND_IP_ADDRESS }}" << 'EOF'
          APP_NAME="weather-api"

          echo "Stopping existing container if running..."
          sudo docker stop "$APP_NAME" || true
          sudo docker rm "$APP_NAME" || true

          echo "Pulling new image from Docker Hub..."
          sudo docker pull "${{ secrets.DOCKER_USERNAME }}/$APP_NAME:latest"

          echo "Starting new container..."
          sudo docker run --name "$APP_NAME" -d -p 8084:8000 "${{ secrets.DOCKER_USERNAME }}/$APP_NAME:latest"
          EOF
